var classes = [
    {
        "name": "AppBundle\\Form\\TaskType",
        "interface": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "lcom": 1,
        "length": 5,
        "vocabulary": 4,
        "volume": 10,
        "difficulty": 0,
        "effort": 0,
        "level": 1.6,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 73.16,
        "mIwoC": 73.16,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Form\\UserType",
        "interface": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "lcom": 1,
        "length": 28,
        "vocabulary": 24,
        "volume": 128.38,
        "difficulty": 0,
        "effort": 0,
        "level": 1.71,
        "bugs": 0.04,
        "time": 0,
        "intelligentContent": 220.08,
        "number_operators": 0,
        "number_operands": 28,
        "number_operators_unique": 0,
        "number_operands_unique": 24,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 65.4,
        "mIwoC": 65.4,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Twig\\IsAllowedToDeleteTaskExtension",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFunctions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Twig_Extension",
            "AppBundle\\Utils\\TaskAuthorizationChecker",
            "Twig_SimpleFunction"
        ],
        "parents": [
            "Twig_Extension"
        ],
        "lcom": 1,
        "length": 8,
        "vocabulary": 6,
        "volume": 20.68,
        "difficulty": 1.5,
        "effort": 31.02,
        "level": 0.67,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 13.79,
        "number_operators": 2,
        "number_operands": 6,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 6,
        "loc": 19,
        "lloc": 13,
        "mi": 104.59,
        "mIwoC": 66.35,
        "commentWeight": 38.23,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\AppBundle",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Symfony\\Component\\HttpKernel\\Bundle\\Bundle"
        ],
        "parents": [
            "Symfony\\Component\\HttpKernel\\Bundle\\Bundle"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Utils\\UserRefresher",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "refreshIfAuthenticated",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorageInterface",
            "AppBundle\\Entity\\User",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"
        ],
        "parents": [],
        "lcom": 1,
        "length": 18,
        "vocabulary": 9,
        "volume": 57.06,
        "difficulty": 5.2,
        "effort": 296.7,
        "level": 0.19,
        "bugs": 0.02,
        "time": 16,
        "intelligentContent": 10.97,
        "number_operators": 5,
        "number_operands": 13,
        "number_operators_unique": 4,
        "number_operands_unique": 5,
        "cloc": 7,
        "loc": 23,
        "lloc": 16,
        "mi": 98.88,
        "mIwoC": 61.17,
        "commentWeight": 37.72,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.17,
        "relativeSystemComplexity": 25.17,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 50.33,
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Utils\\TaskAuthorizationChecker",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isAllowedToDelete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorageInterface",
            "Symfony\\Component\\Security\\Core\\Authorization\\AuthorizationCheckerInterface",
            "AppBundle\\Entity\\Task"
        ],
        "parents": [],
        "lcom": 1,
        "length": 37,
        "vocabulary": 17,
        "volume": 151.24,
        "difficulty": 8.05,
        "effort": 1217.45,
        "level": 0.12,
        "bugs": 0.05,
        "time": 68,
        "intelligentContent": 18.79,
        "number_operators": 14,
        "number_operands": 23,
        "number_operators_unique": 7,
        "number_operands_unique": 10,
        "cloc": 10,
        "loc": 29,
        "lloc": 19,
        "mi": 96.18,
        "mIwoC": 56.71,
        "commentWeight": 39.47,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.42,
        "relativeSystemComplexity": 25.42,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 0.83,
        "totalSystemComplexity": 50.83,
        "pageRank": 0.07,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "AppBundle\\Entity\\Task",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCreatedAt",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setCreatedAt",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTitle",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setTitle",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getContent",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setContent",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isDone",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toggle",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAuthor",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setAuthor",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 12,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 6,
        "nbMethodsSetters": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Datetime",
            "AppBundle\\Entity\\User"
        ],
        "parents": [],
        "lcom": 1,
        "length": 36,
        "vocabulary": 8,
        "volume": 108,
        "difficulty": 3.83,
        "effort": 414,
        "level": 0.26,
        "bugs": 0.04,
        "time": 23,
        "intelligentContent": 28.17,
        "number_operators": 13,
        "number_operands": 23,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 36,
        "loc": 95,
        "lloc": 59,
        "mi": 87.78,
        "mIwoC": 47,
        "commentWeight": 40.78,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 6.42,
        "relativeSystemComplexity": 6.42,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 77,
        "totalSystemComplexity": 77,
        "pageRank": 0.18,
        "afferentCoupling": 3,
        "efferentCoupling": 2,
        "instability": 0.4,
        "violations": {}
    },
    {
        "name": "AppBundle\\Entity\\User",
        "interface": false,
        "methods": [
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUsername",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUsername",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSalt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPassword",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setPassword",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getEmail",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setEmail",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRole",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setRole",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRoles",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "eraseCredentials",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 12,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 5,
        "nbMethodsSetters": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Security\\Core\\User\\UserInterface"
        ],
        "parents": [],
        "lcom": 3,
        "length": 29,
        "vocabulary": 7,
        "volume": 81.41,
        "difficulty": 3.6,
        "effort": 293.09,
        "level": 0.28,
        "bugs": 0.03,
        "time": 16,
        "intelligentContent": 22.61,
        "number_operators": 11,
        "number_operands": 18,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 35,
        "loc": 91,
        "lloc": 56,
        "mi": 89.33,
        "mIwoC": 48.35,
        "commentWeight": 40.98,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 7.33,
        "relativeSystemComplexity": 7.33,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 88,
        "totalSystemComplexity": 88,
        "pageRank": 0.37,
        "afferentCoupling": 4,
        "efferentCoupling": 1,
        "instability": 0.2,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\SecurityController",
        "interface": false,
        "methods": [
            {
                "name": "loginAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loginCheck",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logoutCheck",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 3,
        "length": 18,
        "vocabulary": 10,
        "volume": 59.79,
        "difficulty": 1.75,
        "effort": 104.64,
        "level": 0.57,
        "bugs": 0.02,
        "time": 6,
        "intelligentContent": 34.17,
        "number_operators": 4,
        "number_operands": 14,
        "number_operators_unique": 2,
        "number_operands_unique": 8,
        "cloc": 11,
        "loc": 28,
        "lloc": 17,
        "mi": 101.86,
        "mIwoC": 60.58,
        "commentWeight": 41.27,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.27,
        "relativeSystemComplexity": 16.27,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 0.8,
        "totalSystemComplexity": 48.8,
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\TaskController",
        "interface": false,
        "methods": [
            {
                "name": "listAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "editAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toggleTaskAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deleteTaskAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Entity\\Task",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "AppBundle\\Entity\\Task",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "AppBundle\\Entity\\Task",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "AppBundle\\Entity\\Task",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 92,
        "vocabulary": 21,
        "volume": 404.09,
        "difficulty": 6.33,
        "effort": 2559.26,
        "level": 0.16,
        "bugs": 0.13,
        "time": 142,
        "intelligentContent": 63.8,
        "number_operators": 16,
        "number_operands": 76,
        "number_operators_unique": 3,
        "number_operands_unique": 18,
        "cloc": 15,
        "loc": 69,
        "lloc": 54,
        "mi": 76.34,
        "mIwoC": 43.29,
        "commentWeight": 33.06,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 529,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 529.33,
        "totalStructuralComplexity": 2645,
        "totalDataComplexity": 1.67,
        "totalSystemComplexity": 2646.67,
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\UserController",
        "interface": false,
        "methods": [
            {
                "name": "listAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "editAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Entity\\User",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "AppBundle\\Entity\\User",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 77,
        "vocabulary": 20,
        "volume": 332.79,
        "difficulty": 5.65,
        "effort": 1879.28,
        "level": 0.18,
        "bugs": 0.11,
        "time": 104,
        "intelligentContent": 58.93,
        "number_operators": 13,
        "number_operands": 64,
        "number_operators_unique": 3,
        "number_operands_unique": 17,
        "cloc": 9,
        "loc": 47,
        "lloc": 38,
        "mi": 78.83,
        "mIwoC": 47.47,
        "commentWeight": 31.36,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 324,
        "relativeDataComplexity": 0.32,
        "relativeSystemComplexity": 324.32,
        "totalStructuralComplexity": 972,
        "totalDataComplexity": 0.95,
        "totalSystemComplexity": 972.95,
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\DefaultController",
        "interface": false,
        "methods": [
            {
                "name": "indexAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0.5,
        "effort": 2.38,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 1,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 3,
        "loc": 11,
        "lloc": 8,
        "mi": 111.61,
        "mIwoC": 75.43,
        "commentWeight": 36.18,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\DataFixtures\\ORM\\Fixtures",
        "interface": false,
        "methods": [
            {
                "name": "load",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture",
            "Doctrine\\Common\\Persistence\\ObjectManager",
            "AppBundle\\Entity\\User",
            "AppBundle\\Entity\\User",
            "AppBundle\\Entity\\Task",
            "AppBundle\\Entity\\Task",
            "AppBundle\\Entity\\Task"
        ],
        "parents": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture"
        ],
        "lcom": 1,
        "length": 111,
        "vocabulary": 31,
        "volume": 549.92,
        "difficulty": 1.75,
        "effort": 962.35,
        "level": 0.57,
        "bugs": 0.18,
        "time": 53,
        "intelligentContent": 314.24,
        "number_operators": 6,
        "number_operands": 105,
        "number_operators_unique": 1,
        "number_operands_unique": 30,
        "cloc": 4,
        "loc": 50,
        "lloc": 46,
        "mi": 65.22,
        "mIwoC": 44,
        "commentWeight": 21.21,
        "kanDefect": 0.84,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.08,
        "relativeSystemComplexity": 121.08,
        "totalStructuralComplexity": 121,
        "totalDataComplexity": 0.08,
        "totalSystemComplexity": 121.08,
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    }
]