# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.user_refresher:
        class: AppBundle\Utils\UserRefresher
        arguments: ["@security.token_storage"]

    app.task_authorization_checker:
        class: AppBundle\Utils\TaskAuthorizationChecker
        arguments: ["@security.token_storage", "@security.authorization_checker"]

    app.is_allowed_to_delete_task_extension:
        class: AppBundle\Twig\IsAllowedToDeleteTaskExtension
        arguments: ["@app.task_authorization_checker"]
        tags:
            - { name: twig.extension }